kind: Service
apiVersion: v1
metadata:
  name: {{ template "fluxcloud.fullname" . }}
  labels:
    app: {{ template "fluxcloud.name" . }}
    chart: {{ template "fluxcloud.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ template "fluxcloud.name" . }}
    release: {{ .Release.Name }}
  ports:
  - protocol: TCP
    port: {{ .Values.servicePort }}
    targetPort: {{ .Values.serviceTargetPort }}
